
main:
  debug: False
  settings_module: settings.production
  log_dir: var/log
  log_file: access.log

redis:
  # redis库，默认为0
  db: 0
  host: localhost
  port: 6379
  password: xxxx


rabbitmq: amqp://guest:guest@localhost:5672//

mysql:
  default:
    host: localhost
    port: 3306
    db: asset
    user: root
    password: 123456

  legacy:
    host: localhost
    port: 3306
    db: test
    user: test
    password: xxxx

  external_storage:
    host: localhost
    port: 3306
    db: test
    user: test
    password: xxxx
  online_goods_service:
    host: localhost
    db: online_service
    user: root
    password: 123456

# 分仓回传url
guanyi_warehouse_url: http://10.7.31.17:9090/guanyi/warehouse/
